export const quizData = {
  "Frontend Developer": [
    { id: 1, type: "mcq", question: "Which language structures web page content?", options: ["CSS", "HTML", "JavaScript", "SQL"], answer: "HTML" },
    { id: 2, type: "mcq", question: "Which CSS property changes text color?", options: ["font-color", "color", "text-style", "background"], answer: "color" },
    { id: 3, type: "mcq", question: "Which React hook manages state?", options: ["useEffect", "useState", "useRouter", "useMemo"], answer: "useState" },
    { id: 4, type: "mcq", question: "Which HTML tag creates a link?", options: ["<link>", "<a>", "<href>", "<url>"], answer: "<a>" },
    { id: 5, type: "mcq", question: "Which CSS layout is one-dimensional?", options: ["Grid", "Flexbox", "Table", "Float"], answer: "Flexbox" },
    { id: 6, type: "mcq", question: "Which command starts a Next.js dev server?", options: ["npm start", "npm run dev", "node index.js", "next build"], answer: "npm run dev" },
    { id: 7, type: "mcq", question: "Which attribute gives image description?", options: ["src", "href", "alt", "title"], answer: "alt" },
    { id: 8, type: "mcq", question: "Which method renders lists in React?", options: ["map()", "filter()", "reduce()", "sort()"], answer: "map()" },
    { id: 9, type: "mcq", question: "Which file handles a route in Next.js App Router?", options: ["route.jsx", "page.jsx", "index.html", "main.js"], answer: "page.jsx" },
    { id: 10, type: "mcq", question: "Which CSS unit is relative to parent font size?", options: ["px", "em", "cm", "pt"], answer: "em" },
    { id: 11, type: "blank", question: "CSS stands for ______ Style Sheets.", answer: "Cascading" },
    { id: 12, type: "blank", question: "React components return ______.", answer: "JSX" },
    { id: 13, type: "blank", question: "HTML stands for HyperText ______ Language.", answer: "Markup" },
    { id: 14, type: "blank", question: "The default Next.js local port is ______.", answer: "3000" },
    { id: 15, type: "blank", question: "JavaScript events are handled using event ______.", answer: "handlers" },
    { id: 16, type: "short", question: "What is React used for?", answer: "building user interfaces" },
    { id: 17, type: "short", question: "What is responsive design?", answer: "design that works on different screen sizes" },
    { id: 18, type: "short", question: "What is Tailwind CSS?", answer: "utility-first css framework" },
    { id: 19, type: "short", question: "What is a component?", answer: "reusable ui block" },
    { id: 20, type: "short", question: "What is client-side rendering?", answer: "rendering in the browser" },
  ],

  "Backend Developer": [
    { id: 1, type: "mcq", question: "Which protocol is used for web requests?", options: ["FTP", "HTTP", "SMTP", "SSH"], answer: "HTTP" },
    { id: 2, type: "mcq", question: "Which status code means success?", options: ["200", "404", "500", "301"], answer: "200" },
    { id: 3, type: "mcq", question: "Which method creates data?", options: ["GET", "POST", "DELETE", "PATCH"], answer: "POST" },
    { id: 4, type: "mcq", question: "Which method reads data?", options: ["GET", "POST", "PUT", "DELETE"], answer: "GET" },
    { id: 5, type: "mcq", question: "Which status code means not found?", options: ["200", "201", "404", "500"], answer: "404" },
    { id: 6, type: "mcq", question: "Which database is document-based?", options: ["MySQL", "MongoDB", "SQL Server", "Oracle"], answer: "MongoDB" },
    { id: 7, type: "mcq", question: "What does API stand for?", options: ["Application Programming Interface", "Advanced Program Input", "App Process Internet", "Applied Programming Index"], answer: "Application Programming Interface" },
    { id: 8, type: "mcq", question: "Which format is commonly used in APIs?", options: ["JSON", "DOCX", "PNG", "MP3"], answer: "JSON" },
    { id: 9, type: "mcq", question: "Which tool tests API endpoints?", options: ["Postman", "Photoshop", "Excel", "Figma"], answer: "Postman" },
    { id: 10, type: "mcq", question: "Which HTTP method updates full data?", options: ["GET", "PUT", "POST", "DELETE"], answer: "PUT" },
    { id: 11, type: "blank", question: "CRUD stands for Create, Read, Update, and ______.", answer: "Delete" },
    { id: 12, type: "blank", question: "JSON stands for JavaScript Object ______.", answer: "Notation" },
    { id: 13, type: "blank", question: "A server sends a response after receiving a ______.", answer: "request" },
    { id: 14, type: "blank", question: "Environment variables are often stored in a ______ file.", answer: ".env" },
    { id: 15, type: "blank", question: "Authentication verifies user ______.", answer: "identity" },
    { id: 16, type: "short", question: "What is backend development?", answer: "server-side development" },
    { id: 17, type: "short", question: "What is middleware?", answer: "function between request and response" },
    { id: 18, type: "short", question: "What is authorization?", answer: "checking user permissions" },
    { id: 19, type: "short", question: "What is an endpoint?", answer: "api url" },
    { id: 20, type: "short", question: "What is deployment?", answer: "publishing application online" },
  ],

  "Full Stack Developer": [
    { id: 1, type: "mcq", question: "Full stack means working on frontend and ______.", options: ["Backend", "Excel", "Design only", "Testing only"], answer: "Backend" },
    { id: 2, type: "mcq", question: "Which library is used for UI?", options: ["React", "MongoDB", "Express", "Node"], answer: "React" },
    { id: 3, type: "mcq", question: "Which runs JavaScript on the server?", options: ["Node.js", "HTML", "CSS", "Figma"], answer: "Node.js" },
    { id: 4, type: "mcq", question: "Which database stores collections?", options: ["MongoDB", "HTML", "React", "Tailwind"], answer: "MongoDB" },
    { id: 5, type: "mcq", question: "Which command installs dependencies?", options: ["npm install", "npm build", "git push", "node start"], answer: "npm install" },
    { id: 6, type: "mcq", question: "Which Git command saves changes locally?", options: ["git commit", "git clone", "git pull", "git status"], answer: "git commit" },
    { id: 7, type: "mcq", question: "Which Git command uploads changes?", options: ["git push", "git pull", "git clone", "git init"], answer: "git push" },
    { id: 8, type: "mcq", question: "Which status code means server error?", options: ["500", "200", "301", "201"], answer: "500" },
    { id: 9, type: "mcq", question: "Which framework is used in this project?", options: ["Next.js", "Laravel", "Django", "Angular"], answer: "Next.js" },
    { id: 10, type: "mcq", question: "Which file stores project packages?", options: ["package.json", "README.md", "index.html", ".gitignore"], answer: "package.json" },
    { id: 11, type: "blank", question: "Frontend is what the user ______.", answer: "sees" },
    { id: 12, type: "blank", question: "Backend handles business logic and ______.", answer: "data" },
    { id: 13, type: "blank", question: "GitHub is used for code ______.", answer: "hosting" },
    { id: 14, type: "blank", question: "A full stack developer works on client and ______.", answer: "server" },
    { id: 15, type: "blank", question: "Next.js uses file-based ______.", answer: "routing" },
    { id: 16, type: "short", question: "What is full stack development?", answer: "frontend and backend development" },
    { id: 17, type: "short", question: "What is Git used for?", answer: "version control" },
    { id: 18, type: "short", question: "What is npm?", answer: "package manager" },
    { id: 19, type: "short", question: "What is a database?", answer: "organized collection of data" },
    { id: 20, type: "short", question: "What is an API?", answer: "application programming interface" },
  ],

  "QA Tester": [
    { id: 1, type: "mcq", question: "QA stands for ______.", options: ["Quality Assurance", "Quick Application", "Query Access", "Quality App"], answer: "Quality Assurance" },
    { id: 2, type: "mcq", question: "Which testing checks individual units?", options: ["Unit testing", "UAT", "Regression", "Load testing"], answer: "Unit testing" },
    { id: 3, type: "mcq", question: "Which testing checks the full system flow?", options: ["Integration testing", "Syntax testing", "Style testing", "Image testing"], answer: "Integration testing" },
    { id: 4, type: "mcq", question: "Which document records defects?", options: ["Bug report", "Resume", "Invoice", "Design file"], answer: "Bug report" },
    { id: 5, type: "mcq", question: "Which testing confirms old features still work?", options: ["Regression testing", "Smoke testing", "Unit testing", "Alpha testing"], answer: "Regression testing" },
    { id: 6, type: "mcq", question: "Which testing is done by end users?", options: ["UAT", "Unit testing", "Syntax testing", "Code review"], answer: "UAT" },
    { id: 7, type: "mcq", question: "Which tool can automate browser testing?", options: ["Selenium", "MongoDB", "Photoshop", "Excel"], answer: "Selenium" },
    { id: 8, type: "mcq", question: "What should a test case include?", options: ["Steps and expected result", "Only title", "Only color", "Only image"], answer: "Steps and expected result" },
    { id: 9, type: "mcq", question: "Which testing checks login with wrong password?", options: ["Negative testing", "Positive testing", "Load testing", "UI testing only"], answer: "Negative testing" },
    { id: 10, type: "mcq", question: "Which testing checks app performance under users?", options: ["Load testing", "Unit testing", "Smoke testing", "Manual testing"], answer: "Load testing" },
    { id: 11, type: "blank", question: "A bug is an error or ______ in software.", answer: "defect" },
    { id: 12, type: "blank", question: "Expected result means what should ______.", answer: "happen" },
    { id: 13, type: "blank", question: "Manual testing is done by a ______.", answer: "tester" },
    { id: 14, type: "blank", question: "Retesting checks whether a fixed bug is ______.", answer: "resolved" },
    { id: 15, type: "blank", question: "Test cases are written before executing ______.", answer: "tests" },
    { id: 16, type: "short", question: "What is testing?", answer: "checking software quality" },
    { id: 17, type: "short", question: "What is a test case?", answer: "steps to verify functionality" },
    { id: 18, type: "short", question: "What is a bug report?", answer: "document describing defect" },
    { id: 19, type: "short", question: "What is regression testing?", answer: "testing old features after changes" },
    { id: 20, type: "short", question: "What is UAT?", answer: "user acceptance testing" },
  ],

  "Database Developer": [
    { id: 1, type: "mcq", question: "SQL stands for ______.", options: ["Structured Query Language", "Simple Query Link", "System Query Logic", "Server Quick Language"], answer: "Structured Query Language" },
    { id: 2, type: "mcq", question: "Which command retrieves data?", options: ["SELECT", "INSERT", "DELETE", "UPDATE"], answer: "SELECT" },
    { id: 3, type: "mcq", question: "Which command adds data?", options: ["INSERT", "SELECT", "DROP", "ALTER"], answer: "INSERT" },
    { id: 4, type: "mcq", question: "Which key uniquely identifies a row?", options: ["Primary key", "Foreign key", "Index", "Column"], answer: "Primary key" },
    { id: 5, type: "mcq", question: "Which key connects tables?", options: ["Foreign key", "Primary key", "Null key", "Sort key"], answer: "Foreign key" },
    { id: 6, type: "mcq", question: "Which database is NoSQL?", options: ["MongoDB", "MySQL", "SQL Server", "Oracle"], answer: "MongoDB" },
    { id: 7, type: "mcq", question: "Which SQL command removes a table?", options: ["DROP", "DELETE", "SELECT", "INSERT"], answer: "DROP" },
    { id: 8, type: "mcq", question: "Which clause filters records?", options: ["WHERE", "ORDER BY", "GROUP BY", "JOIN"], answer: "WHERE" },
    { id: 9, type: "mcq", question: "Which clause sorts records?", options: ["ORDER BY", "WHERE", "HAVING", "JOIN"], answer: "ORDER BY" },
    { id: 10, type: "mcq", question: "Which operation combines tables?", options: ["JOIN", "SORT", "FILTER", "DROP"], answer: "JOIN" },
    { id: 11, type: "blank", question: "A table is made of rows and ______.", answer: "columns" },
    { id: 12, type: "blank", question: "Normalization reduces data ______.", answer: "redundancy" },
    { id: 13, type: "blank", question: "MongoDB stores data in ______.", answer: "documents" },
    { id: 14, type: "blank", question: "A database stores organized ______.", answer: "data" },
    { id: 15, type: "blank", question: "The WHERE clause is used to ______ records.", answer: "filter" },
    { id: 16, type: "short", question: "What is a primary key?", answer: "unique identifier" },
    { id: 17, type: "short", question: "What is a foreign key?", answer: "key linking tables" },
    { id: 18, type: "short", question: "What is normalization?", answer: "organizing data to reduce redundancy" },
    { id: 19, type: "short", question: "What is SQL used for?", answer: "managing relational databases" },
    { id: 20, type: "short", question: "What is MongoDB?", answer: "nosql document database" },
  ],
};