import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { getCurrentUserFromRequest } from '@/lib/server/auth/current-user.js'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Career Forge",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currentUser = await getCurrentUserFromRequest()

  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header currentUser={currentUser} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
